server:
  port: 9528
  servlet:
    encoding:
      charset: UTF-8

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.2.204:3306/intelligence_community?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 600000

swagger:
  enable: true

# 海康高空抛物相关
hk:
  host: 127.0.0.1:4443
  appKey: 1111
  appSecret: AA
  # 【业务相关配置】
  eventCode: gkpw
  pushMessageUrl: http://127.0.0.1:9529/recognization/alarmInfo/pushAlarmInfo



minio:
  endpoint: http://30.55.10.102:9001
  accessKey: admin
  secretKey: Xtxk_02787179095
  bucketName: filebucket

#数据银行
datalake:
  config:
    url: http://tlmdatabank.tlm.pcep.cloud
    identity : 4DB4FDA9CF814D39AB21612F5DC61B100006F9A4513E46BEMNQTCNZPGM3DAKZTGIYC4KZSFY2WIKZWMM3WAKZUG5RDKYJOF4YV6NBUGEXT22ZQOBQGWYDPMRZXE4JRMNVXAZTBGQXWKYZXGBRTAMBTGEZC4MBQGUXTONZXFYXTAMBSF4YDAMQ
    #应用的id及私钥用户获取token
    clientId: ec391582-5420-407f-8e9b-69d7c013a663
    clientSecret: msmfcbj2hu9devjcr33nbr1r
    proxyIp: 172.16.0.207
    proxyPort: 8080

# xxl-job
xxl:
  job:
    accessToken: default_token # 执行器通讯TOKEN [选填]：非空时启用；
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: third-data-service
      address:
      ip:  # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      port: 9999  # ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      logpath: /logs/xxl-job # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logretentiondays: 30 # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；