server:
  port: 9528
  servlet:
    encoding:
      charset: UTF-8

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.2.204:3306/intelligence_community?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

swagger:
  enable: true