spring:
  application:
    name: third-data-service
  profiles:
    active: dev
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 50MB
      # 设置总上传的文件大小
      max-request-size: 100MB
  jackson:
    time-zone: GMT+8

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.xtxk.cn.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  #configuration:
    #mybatis输出sql语句
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 日志配置
logging:
  level:
    root: info
  config: classpath:logback.xml
  file:
    path: /logs/third-data-service/
    name: third-data-service


